config/routes.rb
Sap4::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :pivots, only: [ :create, :destroy]

  get "static_pages/home"

  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"

  root to: 'static_pages#home'
  match '/home' => 'static_pages#home'
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: :delete
  match '/signup' => 'users#new'
  match '/help' => 'static_pages#help'
  match '/about' => 'static_pages#about'
  match '/contact' => 'static_pages#contact'

end

app/models/pivot.rb
class Pivot < ActiveRecord::Base
   attr_accessible :content
   belongs_to :user
   validates :user_id, presence: true

   validates :content, presence: true, length: { maximum: 500 }

   default_scope order: 'pivots.created_at DESC'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  role            :string(255)
#  company         :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
   attr_accessible :name, :email, :role, :company, :password, :password_confirmation, :remember_token
   has_secure_password
   has_many :pivots, dependent: :destroy

   before_save :create_remember_token

   validates :name, :email, :role, :company, presence: true

   private

      def create_remember_token
          self.remember_token = SecureRandom.urlsafe_base64
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pivots_controller.rb
class PivotsController < ApplicationController
   before_filter :signed_in_user

   def create
	    @pivot = current_user.pivots.build(params[:pivot])
	    if @pivot.save
	      flash[:success] = "Pivot created!"
	      redirect_to current_user
	    else
	      render current_user
	    end
   end


   def destroy
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
      user = User.find_by_email(params[:session][:email])
      if user && user.authenticate(params[:session][:password])
	 sign_in user
	 redirect_back_or user
      else
	 flash.now[:error] = 'Invalid email/password combination'
	 render 'new'
      end
  end

  def destroy
      sign_out
      redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user, only: [:edit, :update]


  def new
     @user = User.new
  end

  def edit
  end

  def index
     @users = User.paginate(page: params[:page], per_page: 15)
  end

  def show
     @user= User.find(params[:id])
     @pivot = current_user.pivots.build if signed_in?
     @pivots = @user.pivots.paginate(page: params[:page], per_page: 5)
  end

  def destroy
     User.find(params[:id]).destroy
     flash[:success] = "User deleted!"
     redirect_to users_path
  end

  def create
     @user = User.new(params[:user])
     if @user.save
	sign_in @user
        flash[:success] = "Welcome to Pivot IT!"
        redirect_to @user
     else
        render 'new'
     end
  end

  def update 

     if @user.update_attributes(params[:user])
	flash[:success] = "Profile changed"
	sign_in @user
	redirect_to @user
     else
	render 'edit'
     end     
  end


  private 
     

     def correct_user
         @user = User.find(params[:id])
         redirect_to(root_path) unless current_user?(@user)
     end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)    
    base_title = "Pivot IT"
    if page_title.empty? 
       base_title
    else
       "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

   def sign_in(user)
	cookies.permanent[:remember_token] = user.remember_token
	current_user = user 	
   end

   def sign_out
	cookies.delete(:remember_token) 
	current_user = nil 	
   end

   def current_user=(user)
       @current_user = user
   end

   def current_user
       @current_user ||= user_from_remember_token
   end

   def current_user?(user)
       current_user ==  user
   end

   def signed_in?
	!current_user.nil?
   end

   def signed_in_user
        unless signed_in?
	   store_location
	   redirect_to signin_path, notice: "Please sign in." unless signed_in?
	end
   end

   def redirect_back_or(default)
	redirect_to (session[:return_to] || default)
        clear_return_to
   end

   def store_location
       session[:return_to] = request.fullpath
   end

   private

      def user_from_remember_token
	 remember_token = cookies[:remember_token]
	 User.find_by_remember_token(remember_token) unless remember_token.nil?
      end

      def  clear_return_to
           session.delete(:return_to)
      end  	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
     <footer class="footer">
               <small>
			Redefining Lead Generation and Qualification 
	       </small> 
		<nav class="center">
		    <ul class="center">
			<li><%= link_to "About", about_path %> </li>
			<li><%= link_to "Contact", contact_path %> </li>
			<li><%= link_to "News", '#' %> </li>
		    </ul>
		</nav>
     </footer>  

app/views/layouts/_header.html.erb
     <header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
	     <div class="container">
		<%= link_to "Pivot IT", root_path, id: "logo" %>
		<nav>
		    <ul class="nav pull-right">


			<% if signed_in? %>
    			    <li><%= link_to "Home", current_user %> </li>
			    <li><%= link_to "Help", help_path %> </li>
			    <li> <%= link_to "Users", users_path %> </li>
			    <li id="fat-menu" class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Account <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
				    <li><%= link_to "Profile", current_user %></li>
				    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
				    <li class="divider"></li>
				    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
				</ul>
			    </li>
 			<% else %>
    			    <li><%= link_to "Home", root_path %> </li>
			    <li><%= link_to "Help", help_path %> </li>
			    <li><%= link_to "Sign in", signin_path %> </li>
			<% end %>
		    </ul>
		</nav>	     
	     </div>
 	</div> 
     </header>  

app/views/layouts/_shim.html.erb
  <!-- [if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>   
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
     <%= render "layouts/header" %>
     <div class="container">  
	<% flash.each do |key, value| %>
     	   <div class="alert alert-<%= key %>"><%= value %> </div>
	<% end %>
	<%= yield %>
        <%= render "layouts/footer" %>
        <%= debug(params) if Rails.env.development? %>
     </div>
</body>
</html>

app/views/pivots/_pivot.html.erb
<li>
   <span class="content"><%= pivot.content %></span>
   <span class="timestamp">
	Posted <%= time_ago_in_words(pivot.created_at) %> ago.
   </span>
</li>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
     <div class="alert alert-<%= key %>"><%= value %> </div>
<% end %>

app/views/shared/_pivot_form.html.erb
<%= form_for(@pivot) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_field :content, placeholder: "Compose new Pivot..." %>
  <%= f.submit "Create Pivot", class: "btn btn-large btn-primary" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
  <h1>About Us</h1>
  <p>
   This is the About page for my application.
  </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
  <h1>Contact</h1>
  <h2>
   This is the Contact page for my application.
  </h2>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
  <h1>Help</h1>
  <p>
   This is the help page for my application.
  </p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Pivot IT</h1>
  <h2>
	Welcome to Pivot IT.
  </h2>
  <%= link_to image_tag("logo.gif", alt: "Pivot"), '#' %> <br/>
  <%= link_to "Sign in or Sign up", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>
<div class="row">
    <div class="span6 offset3">     
       <%= form_for(@user) do |f| %>
         <%= render 'shared/error_messages', :object => f.object %>

	 <%= f.label :name %>
	 <%= f.text_field :name %>

	 <%= f.label :email %>
	 <%= f.text_field :email %>

	 <%= f.label :password %>
	 <%= f.password_field :password %>

	 <%= f.label :password_confirmation, "Confirmation" %>
	 <%= f.password_field :password_confirmation %>

	 <%= f.label :role %>
	 <%= f.text_field :role %>

	 <%= f.label :company %>
	 <%= f.text_field :company %>

         <br/>
    	 <%= f.submit "Save changes", :class => "btn btn-large brn-primary" %>
       <% end %>

	<%= gravatar_for @user %>
      	<a href="http://gravatar.com/emails">change your gravatar</a>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1> All users </h1>

<%= will_paginate %>
<table>
   <tr>
       <th> Num </th>
       <th > Name </th>
       <th> Role </th>
       <th> Company </th>
       <% if current_user.admin?  %>
          <th> Action </th>
       <% end %>  
   </tr>
   <% @users.each do |f| %>
     <tr>
       <td class="td_id"> <%= f.id %> </td>
       <td class="td_name"> <%= f.name %> </td>
       <td class="td_role"> <%= f.role %> </td>
       <td class="td_comp"> <%= f.company %> </td>
       <% if current_user.admin? && !current_user?(f) %>
          <td> <%= link_to "delete", f, method: :delete, confirm: "Are you sure?" %> </td>
       <% end %> 
     </tr>
   <% end %>
</table>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
    <div class="span6 offset3">     
       <%= form_for(@user) do |f| %>
         <%= render 'shared/error_messages' %>

	 <%= f.label :name %>
	 <%= f.text_field :name %>

	 <%= f.label :email %>
	 <%= f.text_field :email %>

	 <%= f.label :password %>
	 <%= f.password_field :password %>

	 <%= f.label :password_confirmation, "Confirmation" %>
	 <%= f.password_field :password_confirmation %>

	 <%= f.label :role %>
	 <%= f.text_field :role %>

	 <%= f.label :company %>
	 <%= f.text_field :company %>

         <br/>
    	 <%= f.submit "Create my account", :class => "btn btn-large brn-primary" %>

       <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
   <aside class="span4">
       <section>
	  <h1>
	    <%= @user.name %> 
	  </h1>
          <h2>
		 ( <%= @user.role %> at <%= @user.company %> ) 
	  </h2>
  
   </aside>
</div>
<div>
<table class="pivots">
<tr>
<th>
   Create a Pivot
</th>
<th>
       <% if @user.pivots.any? %>	
	 My Pivots (<%= @user.pivots.count %>)
       <% end %>   
</th>
</tr>
<tr>
<td>
   <%= render 'shared/pivot_form' %>
</td>
<td>
   <div class="span8">
       <% if @user.pivots.any? %>		     
             <ol class="pivots">
		<%= render @pivots %>
	     </ol>	
	     <%= will_paginate @pivots %>
       <% end %>
   </div>
</td>
</tr>
</table>
</div>